services:
  packpoint:
    image: spuder/packpoint:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: packpoint
    ports:
      - "9292:9292"
    env_file:
      - .env
    network_mode: host
    # networks:
    #   - packpoint

  # tailscale:
  #   image: tailscale/tailscale:v1.86
  #   container_name: packpoint-tailscale
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #   volumes:
  #     - ./tailscale/varlib-packpoint:/var/lib/tailscale
  #     - ./tailscale/tmp-packpoint:/tmp
  #   environment:
  #     - TS_AUTHKEY=${TS_AUTH_KEY}
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_HOSTNAME

  #   networks:
  #     - packpoint
  #   command: tailscaled

# networks:
#   packpoint:
#     driver: bridge
#   app-network:
#     driver: bridge

# podman build -t spuder/packpoint . --no-cache
# podman run --env-file .env -p 9292:9292 localhost/spuder/packpoint:latest