# Corrected Docker Compose file for Packpoint with Tailscale sidecar

services:
  # The main application container
  packpoint:
    image: spuder/packpoint:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: packpoint${DEPLOY_ENV:+-$DEPLOY_ENV}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/Denver
    networks:
      - ${APP_ENV:+packpoint-$APP_ENV}${APP_ENV:-packpoint}

  # This service generates the configuration file for tailscale serve
  tailscale-config-init:
    image: bash
    container_name: tailscale-config-init-packpoint${DEPLOY_ENV:+-$DEPLOY_ENV}
    entrypoint:
      - bash
      - -c
      - |
        # Generate the configuration file. We use the service name 'packpoint'
        # to connect to the other container on the shared network.
        echo '{
          "TCP": {
            "443": {"HTTPS": true},
            "80": {"HTTP": true}
          },
          "Web": {
            "${TAILSCALE_DOMAIN}:443": {
              "Handlers": {
                "/": {"Proxy": "http://packpoint${DEPLOY_ENV:+-$DEPLOY_ENV}:9292"}
              }
            },
            "${TAILSCALE_DOMAIN}:80": {
              "Handlers": {
                "/": {"Proxy": "http://packpoint${APP_ENV:+-$APP_ENV}:9292"}
              }
            }
          }
        }' > /tailscale-config/serve-config.json
        cat /tailscale-config/serve-config.json
    volumes:
      - ${APP_ENV:+tailscale-config-$APP_ENV}${APP_ENV:-tailscale-config}:/tailscale-config
    env_file:
      - .env
    restart: "no"
    network_mode: "none"

  tailscale:
    image: tailscale/tailscale:v1.86
    container_name: packpoint-tailscale${DEPLOY_ENV:+-$DEPLOY_ENV}
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./tailscale/varlib-packpoint:/var/lib/tailscale
      - ./tailscale/tmp-packpoint:/tmp
      - ${APP_ENV:+tailscale-config-$APP_ENV}${APP_ENV:-tailscale-config}:/tailscale-config:ro
    environment:
      - TS_AUTHKEY=${TS_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=packpoint-web
      - TS_ACCEPT_DNS=false
      - TS_SERVE_CONFIG=/tailscale-config/serve-config.json
    networks:
      - ${APP_ENV:+packpoint-$APP_ENV}${APP_ENV:-packpoint}
    depends_on:
      - tailscale-config-init
      - packpoint

networks:
  packpoint:
    driver: bridge
  packpoint-dev:
    driver: bridge

volumes:
  tailscale-config:
  tailscale-config-dev:
