# Corrected Docker Compose file for Packpoint with Tailscale sidecar

services:
  # The main application container
  packpoint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: packpoint${DEPLOY_ENV:+-$DEPLOY_ENV}
    restart: unless-stopped
    # env_file:
    #   - .env
    environment:
      - TZ=America/Denver
      - TINDIE_USERNAME=${TINDIE_USERNAME}
      - EASYPOST_PROD_API_KEY=${EASYPOST_PROD_API_KEY}
      - EASYPOST_PROD_FROM_ADDRESS=${EASYPOST_PROD_FROM_ADDRESS}
      - RACK_ENV=production
      - APP_ENV=production
      - DEPLOY_ENV=production
      - RAILS_ENV=production
      - ALLOWED_HOSTS=packpoint.snowy-vibes.ts.net,packpoint.local,localhost
      - CUPS_HOST=${CUPS_HOST} #TODO: is this even needed?
    # ports:
    #   - "9292:9292"
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=packpoint"
      - "docktail.service.port=9292"
      - "docktail.service.service-port=443"
