version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9292:9292"
    volumes:
      - .:/app
    env_file:
      - stack.env
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
