source 'https://rubygems.org'

gem 'dotenv'
gem 'easypost', '~> 6.4.1'
gem 'sinatra', '~> 4.1.1'
gem 'vcr', '~> 6.3.1'
gem 'webmock'
gem 'faker'
gem 'digest'
gem 'rackup'
gem 'cupsffi'
gem 'puma'
gem 'tindie_api', '~> 0.1.12'
# gem 'tindie_api', path: '../tindie_api'
